FROM --platform=linux/amd64 ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

RUN dpkg --add-architecture arm64 && \
    DEBIAN_FRONTEND=noninteractive apt-get \
      -o Acquire::CompressionTypes::Order::=gz \
      update && \
    DEBIAN_FRONTEND=noninteractive apt-get \
      -o Acquire::CompressionTypes::Order::=gz \
      -y \
      --no-install-recommends \
      install \
        libpango-1.0-0:arm64 \
        libpango1.0-dev:arm64 \
        libgtk-3-dev:arm64
