FROM --platform=linux/amd64 ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main@sha256:ac4b559a686670def8b2ce14e188e695d76bd1e370c8f1e8fc362da4991894c3

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
    libpango-1.0-0 \
    libpango1.0-dev \
    libgtk-3-dev
