FROM --platform=linux/amd64 ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main@sha256:fbb73fb69457483ccd15d8b880c69ce7d76f3a57be3f9f850be1c63305344f03

RUN dpkg --add-architecture armhf && \
    DEBIAN_FRONTEND=noninteractive apt-get \
      -o Acquire::CompressionTypes::Order::=gz \
      update && \
    DEBIAN_FRONTEND=noninteractive apt-get \
      -o Acquire::CompressionTypes::Order::=gz \
      -y \
      --no-install-recommends \
      install \
        libpango-1.0-0:armhf \
        libpango1.0-dev:armhf \
        libgtk-3-dev:armhf
