FROM --platform=linux/amd64 ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main@sha256:4f40e6ec3b812f1d70cbf2d33346c4fae9f278e38b63491059fa2b961e801101

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
    libpango-1.0-0 \
    libpango1.0-dev \
    libgtk-3-dev
