FROM --platform=linux/amd64 ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main@sha256:daa2a0071788ec7fd172b73fc777b661c8b7d037ec2aac84e2fac6bc540723bd

RUN dpkg --add-architecture armhf && \
    DEBIAN_FRONTEND=noninteractive apt-get \
      -o Acquire::CompressionTypes::Order::=gz \
      update && \
    DEBIAN_FRONTEND=noninteractive apt-get \
      -o Acquire::CompressionTypes::Order::=gz \
      -y \
      --no-install-recommends \
      install \
        libpango-1.0-0:armhf \
        libpango1.0-dev:armhf \
        libgtk-3-dev:armhf
