FROM --platform=linux/amd64 ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main@sha256:603799cf002120f5cb3271112ceffd5cedef5c428d5652b4aa9753953df42a82

RUN dpkg --add-architecture armhf && \
    DEBIAN_FRONTEND=noninteractive apt-get \
      -o Acquire::CompressionTypes::Order::=gz \
      update && \
    DEBIAN_FRONTEND=noninteractive apt-get \
      -o Acquire::CompressionTypes::Order::=gz \
      -y \
      --no-install-recommends \
      install \
        libpango-1.0-0:armhf \
        libpango1.0-dev:armhf \
        libgtk-3-dev:armhf
