[build]
# Set explicit target while developing for platform other than host platform
#target = "aarch64-pc-windows-msvc"
#target = "aarch64-unknown-linux-gnu"
#target = "aarch64-apple-darwin"

#[target.'cfg(all(windows, target_env = "msvc"))']
#rustflags = ["-C", "target-feature=+crt-static"]